title: <p align="center"> Pinindu Wekunagoda </p>

logo: "/images/IMG-6501.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanhtran">GitHub</a>
  </p>
  
  <p align="justify">
 Hello there! I am a freelance ML engineer with a specialization in computer vision (CV) and natural language processing (NLP). 
 I have a strong passion for working with data and developing algorithms that can learn from it to make intelligent decisions.
  <br><br>
  Currently, I am pursuing a BSc Honors degree in Computer Science at the University of Westminster, 
  where I have been expanding my knowledge and skills in the field of AI and ML. Through my studies, 
  I have gained a deep understanding of the theoretical foundations of ML and have developed strong programming skills to 
  apply that knowledge in practice.
  <br><br>
  I am always looking for new and exciting projects that allow me to push the boundaries of what is possible with ML. My goal is to help my clients achieve their goals through the use of intelligent algorithms that can learn from data and make accurate predictions.
  If you are interested in working with me, feel free to reach out. I would love to hear about your project and see how I can help.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: # Google Analytics tracking ID
