title: <p align="center"> Pinindu Wekunagoda </p>

logo: "/images/pict.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/pinindu-wekunagoda/">LinkedIn</a> |
  <a href="https://github.com/pininduwk">GitHub</a>
  </p>
  
  <p align="justify">
 Hello there! I am a freelance ML engineer with a specialization in computer vision (CV) and natural language processing (NLP). 
 I have a strong passion for working with data and developing algorithms that can learn from it to make intelligent decisions.
  <br><br>
  Currently, I am pursuing a BSc Honors degree in Computer Science at the University of Westminster, 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: # Google Analytics tracking ID
